spring:
  h2:
    console:
      enabled: true
      path: /console
  application:
    name: library-app
  datasource:
    url: jdbc:h2:file:./libarydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
